/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Configurations;
import Classes.FormatoNumerico;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.JOptionPane;

/**
 *
 * @author terra
 */
public class Cobrar extends javax.swing.JDialog {

    /**
     * Creates new form Cobrar
     */
    double result;
    int state;
    String impresora;
    int tamanoHoja;

    public String getImpresora() {
        return impresora;
    }

    public void setImpresora(String impresora) {
        this.impresora = impresora;
    }

    public int getTamanoHoja() {
        return tamanoHoja;
    }

    public void setTamanoHoja(int tamanoHoja) {
        this.tamanoHoja = tamanoHoja;
    }

    public double getResult() {
        return result;
    }

    public int getState() {
        return state;
    }

    public Cobrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        txtPayWith.setTransferHandler(null);
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
        result = 0;
        state = 0;
        loadPrinterSize();
    }

    public void loadPrinterSize() {
        String[] datos = new Configurations().getTicketConfigs();
        switch (datos[1]) {
            case "3":
                cmbSizes.setSelectedIndex(0);
                break;
            case "2":
                cmbSizes.setSelectedIndex(1);
                break;
            case "1":
                cmbSizes.setSelectedIndex(2);
                break;
        }
    }
    
    public void asign_dat(String Final) {
        lblFinalPrice.setText(Final);
        cargar_impresoras();
    }

    public void setAbonar(String Adelantado) {
        jLabel1.setText("DATOS DE ABONO");
        lblFinalPrice.setText(Adelantado);
        cargar_impresoras();
    }

    public void cargar_impresoras() {
        combo_printers.removeAllItems();
        PrintService[] ps = PrintServiceLookup.lookupPrintServices(null, null);
        PrintService defaultPrintService = PrintServiceLookup.lookupDefaultPrintService();
        for (PrintService p : ps) {
            combo_printers.addItem(p.getName());
            if ((p.getName().equals(defaultPrintService.getName()))) {
                combo_printers.setSelectedItem(p.getName());
            }
        }
        combo_printers.addItem("No Imprimir");
        combo_printers.addItem("Imprimir como PDF");
        asignar_defaultprinter();
    }

    public void asignar_defaultprinter() {
        String[] dticket = new Configurations().getTicketConfigs();
        for (int i = 0; i < combo_printers.getItemCount(); i++) {
            String impresora_posicion = combo_printers.getItemAt(i);
            if (impresora_posicion.equals(dticket[0])) {
                combo_printers.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPayWith = new javax.swing.JTextField();
        combo_printers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFinalPrice = new javax.swing.JLabel();
        txtCambio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbSizes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asistente de pago");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE PAGO");

        txtPayWith.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        txtPayWith.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPayWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayWithActionPerformed(evt);
            }
        });
        txtPayWith.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayWithKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPayWithKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPayWithKeyTyped(evt);
            }
        });

        combo_printers.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        combo_printers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imprimir como PDF" }));
        combo_printers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_printersKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("SU CAMBIO ES:");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("CONTINUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("PRECIO FINAL");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("SE PAGO CON");

        lblFinalPrice.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        lblFinalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFinalPrice.setText("0.00");

        txtCambio.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        txtCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCambio.setText("$0");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("SEL. IMPRESORA");

        cmbSizes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbSizes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoja 50 mm", "Hoja 80 mm", "Hoja Carta" }));

        jLabel6.setText("TAMANO IMPRESION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFinalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtPayWith))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(combo_printers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSizes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFinalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPayWith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_printers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbSizes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPayWithKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayWithKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtPayWith.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPayWithKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cobrar();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void cobrar() {
        try {
            if (!"".equals(txtPayWith.getText()) && Double.parseDouble(txtPayWith.getText()) >= Double.parseDouble(new FormatoNumerico().RemoverFormatoMoneda(lblFinalPrice.getText()))) {
                asign_datos();
            } else {
                txtPayWith.setBackground(Color.yellow);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void asign_datos() {
        if (Double.parseDouble(txtPayWith.getText()) >= Double.parseDouble(new FormatoNumerico().RemoverFormatoMoneda(lblFinalPrice.getText()))) {
            result = Double.parseDouble(new FormatoNumerico().RemoverFormatoMoneda(txtPayWith.getText()));
            state = 1;
            setImpresora(combo_printers.getSelectedItem().toString());
            setTamanoHoja(cmbSizes.getSelectedIndex());
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "El monto ingresado es menor o igual al coste a pagar... por favor, corríjalo y continúe…", "¡Atención!", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void txtPayWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayWithActionPerformed
        cobrar();
    }//GEN-LAST:event_txtPayWithActionPerformed

    private void txtPayWithKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayWithKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            int resp = JOptionPane.showConfirmDialog(null, "¿seguro que deseas cancelar?", "Cancelar", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_txtPayWithKeyPressed

    private void combo_printersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_printersKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            asign_datos();
        }
    }//GEN-LAST:event_combo_printersKeyPressed

    public boolean mostrarMensaje(String titulo, String cont, int tipo) {
        MensajeSiNo mensaje = new MensajeSiNo(null, true);
        mensaje.setData(titulo, cont, tipo);
        mensaje.show();
        return mensaje.isResp();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        if (mostrarMensaje("CANCELAR ORDEN", "DESEA CANCELAR ORDEN?", 0)) {
            this.dispose();
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPayWithKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayWithKeyReleased
        if (!txtPayWith.getText().equals("")) {
            if (Double.parseDouble(txtPayWith.getText()) < Double.parseDouble(new FormatoNumerico().RemoverFormatoMoneda(lblFinalPrice.getText()))) {
                txtPayWith.setBackground(Color.RED);
                txtPayWith.setForeground(Color.WHITE);
            } else {
                txtPayWith.setBackground(Color.WHITE);
                txtPayWith.setForeground(Color.BLACK);
            }
            recalc_total();
        } else {
            txtCambio.setText(new FormatoNumerico().AsignarFormatoMoneda("0"));
            recalc_total();
        }
    }//GEN-LAST:event_txtPayWithKeyReleased

    public void recalc_total() {
        if (!txtPayWith.getText().equals("")) {
            double total = Double.parseDouble(txtPayWith.getText()) - Double.parseDouble(new FormatoNumerico().RemoverFormatoMoneda(lblFinalPrice.getText()));
            txtCambio.setText(String.valueOf(new FormatoNumerico().AsignarFormatoMoneda(total + "")));
        } else {
            txtCambio.setText(new FormatoNumerico().AsignarFormatoMoneda("0"));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cobrar dialog = new Cobrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSizes;
    private javax.swing.JComboBox<String> combo_printers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel txtCambio;
    private javax.swing.JTextField txtPayWith;
    // End of variables declaration//GEN-END:variables
}
