/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.DatEmpresa;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author terra
 */
public class DatEmpresa1 extends javax.swing.JDialog {

    int continuar;

    /**
     * Creates new form Datos_Tienda
     */
    public DatEmpresa1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txt_rfc.setTransferHandler(null);
        txt_tel.setTransferHandler(null);
        this.setTitle("Actualizar Datos de la Empresa");
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
        txt_direccion.setLineWrap(true);
    }

    public int getContinuar() {
        return continuar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_direccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ntienda = new javax.swing.JTextField();
        txt_rfc = new javax.swing.JTextField();
        txt_sucursal = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chk_rfc = new javax.swing.JCheckBox();
        chk_tel = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar datos de la tienda");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("NOMBRE O RAZÓN SOCIAL");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("ENCARGADO O RESPONSABLE");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("REGISTRO FEDERAL DE CONTRIBUYENTES");

        txt_direccion.setColumns(20);
        txt_direccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_direccion.setRows(5);
        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_direccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_direccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txt_direccion);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("DIRECCIÓN");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("TELEFONO PRINCIPAL");

        txt_ntienda.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_ntienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ntiendaActionPerformed(evt);
            }
        });
        txt_ntienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ntiendaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ntiendaKeyTyped(evt);
            }
        });

        txt_rfc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_rfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rfcActionPerformed(evt);
            }
        });
        txt_rfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rfcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rfcKeyTyped(evt);
            }
        });

        txt_sucursal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sucursalActionPerformed(evt);
            }
        });
        txt_sucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sucursalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sucursalKeyTyped(evt);
            }
        });

        txt_tel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAMBIA LOS DATOS DE LA EMPRESA");

        chk_rfc.setText("SIN RFC");
        chk_rfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_rfcActionPerformed(evt);
            }
        });

        chk_tel.setText("SIN TEL");
        chk_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_telActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sucursal)
                            .addComponent(txt_ntienda)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_rfc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_rfc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_tel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_tel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ntienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_rfc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_tel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_telKeyTyped

    public void setDatFirstUse() {
        jLabel1.setText("ASIGNA TUS DATOS A LA EMPRESA");
    }

    public void asign_datos() {
        try {
            String[] datos = new DatEmpresa().getDatEmpresa();
            txt_ntienda.setText(datos[1]);
            if ("SIN RFC".equals(datos[2])) {
                txt_rfc.setText(datos[2]);
                chk_rfc.setSelected(true);
                txt_rfc.setEditable(false);
            } else {
                txt_rfc.setText(datos[2]);
            }

            txt_sucursal.setText(datos[3]);
            txt_direccion.setText(datos[4]);
            if ("SIN TELEFONO".equals(datos[5])) {
                txt_tel.setText(datos[5]);
                chk_tel.setSelected(true);
                txt_tel.setEditable(false);
            } else {
                txt_tel.setText(datos[5]);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void txt_ntiendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ntiendaKeyTyped
        if (txt_ntienda.getText().length() >= 35) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ntiendaKeyTyped

    private void txt_rfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rfcKeyTyped
        if (txt_rfc.getText().length() >= 35) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_rfcKeyTyped

    private void txt_sucursalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sucursalKeyTyped
        if (txt_sucursal.getText().length() >= 35) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_sucursalKeyTyped

    private void txt_ntiendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ntiendaKeyReleased

    }//GEN-LAST:event_txt_ntiendaKeyReleased

    private void txt_rfcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rfcKeyReleased

    }//GEN-LAST:event_txt_rfcKeyReleased

    private void txt_sucursalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sucursalKeyReleased

    }//GEN-LAST:event_txt_sucursalKeyReleased

    private void txt_direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyReleased

    }//GEN-LAST:event_txt_direccionKeyReleased

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped

    }//GEN-LAST:event_txt_direccionKeyTyped

    private void txt_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            evt.consume();
            txt_tel.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            txt_tel.requestFocus();
        }
    }//GEN-LAST:event_txt_direccionKeyPressed

    private void chk_rfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_rfcActionPerformed
        if (chk_rfc.isSelected()) {
            txt_rfc.setText("SIN RFC");
            txt_rfc.setEditable(false);
            txt_sucursal.requestFocus();
        } else {
            txt_rfc.setEditable(true);
            txt_rfc.setText("");
            txt_rfc.requestFocus();
        }
    }//GEN-LAST:event_chk_rfcActionPerformed

    private void chk_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_telActionPerformed
        if (chk_tel.isSelected()) {
            txt_tel.setText("SIN TELEFONO");
            txt_tel.setEditable(false);
            btnGuardar.requestFocus();
        } else {
            txt_tel.setEditable(true);
            txt_tel.setText("");
            txt_tel.requestFocus();
        }
    }//GEN-LAST:event_chk_telActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        saveData();
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void saveData() {
        try {
            String nuevo_registro = "123456," + txt_ntienda.getText().replace(',', ' ') + "," + txt_rfc.getText().replace(',', ' ') + "," + txt_sucursal.getText().replace(',', ' ') + "," + txt_direccion.getText().replace(',', ' ') + "," + txt_tel.getText() + ",";
            if ("".equals(txt_ntienda.getText().replace(" ", "") ) || "".equals(txt_rfc.getText().replace(" ", "")) 
                    || "".equals(txt_sucursal.getText().replace(" ", "")) || "".equals(txt_direccion.getText().replace(" ", "")) 
                    || "".equals(txt_tel.getText().replace(" ", ""))) {
                JOptionPane.showMessageDialog(null, "<html><h1>¡CUIDADO FALTAN DATOS!</h1><font SIZE=5><p> Falta escribir algún dato en tu formulario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
            } else {
                new DatEmpresa().setDatEmpresa(nuevo_registro);
                continuar = 1;
                JOptionPane.showMessageDialog(null, "<html><h1>DATOS GUARDADOS</h1><font SIZE=5><p> Datos guardados correctamente</font></html>", "", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        continuar = 2;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txt_ntiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ntiendaActionPerformed
        txt_rfc.requestFocus();
    }//GEN-LAST:event_txt_ntiendaActionPerformed

    private void txt_rfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rfcActionPerformed
        txt_sucursal.requestFocus();
    }//GEN-LAST:event_txt_rfcActionPerformed

    private void txt_sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sucursalActionPerformed
        txt_direccion.requestFocus();
    }//GEN-LAST:event_txt_sucursalActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        saveData();
    }//GEN-LAST:event_txt_telActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatEmpresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatEmpresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatEmpresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatEmpresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatEmpresa1 dialog = new DatEmpresa1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chk_rfc;
    private javax.swing.JCheckBox chk_tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_direccion;
    private javax.swing.JTextField txt_ntienda;
    private javax.swing.JTextField txt_rfc;
    private javax.swing.JTextField txt_sucursal;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
