/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Encryptor;
import Classes.Usuarios;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author ATENEA
 */
public class newUser extends javax.swing.JDialog {

    /**
     * Creates new form newUser
     */
    int continuar = 0;

    public int getContinuar() {
        return continuar;
    }

    public void setContinuar(int continuar) {
        this.continuar = continuar;
    }

    boolean ok = false;

    public boolean isOk() {
        return ok;
    }

    public newUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void createUser() {
        btnUpdate.setVisible(false);
        txt_id.setText(new Usuarios().genID());
    }

    public void editUser(String[] user) {
        btnCreate.setVisible(false);
        txt_id.setText(user[0]);
        txt_username.setText(user[1]);
        txt_pass.setText(user[2]);
        cmbRole.setSelectedItem(user[3]);
//        if ("Empleado".equals(user[3])) {
//            cmbRole.setSelectedIndex(0);
//        } else if ("Administrador".equals(user[3])) {
//            cmbRole.setSelectedIndex(1);
//        }
    }

    public void setDatFirstUse() {
        jLabel1.setText("CREAR CUENTA ADMIN");
        createUser();
        cmbRole.setSelectedItem("Administrador");
        cmbRole.enable(false);
        this.setDefaultCloseOperation(0);
        txt_username.setText("admin");
        txt_pass.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        txt_pass = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        txt_rep_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Datos de cuenta: ");

        btnCreate.setText("CONTINUAR");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR CUENTA NUEVA");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Puesto");

        txt_id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_id.setText("000000000000");

        cmbRole.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Administrador" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        txt_pass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Rep. Cont");

        txt_rep_pass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_rep_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rep_passActionPerformed(evt);
            }
        });
        txt_rep_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rep_passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rep_passKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Identificador");

        txt_username.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_username))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pass)
                                    .addComponent(txt_rep_pass)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_id)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rep_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        storeUser();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        txt_rep_pass.requestFocus();
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        String cadena = (txt_pass.getText()).toUpperCase();
        txt_pass.setText(cadena);
        if (txt_pass.getText().isEmpty()) {
            txt_pass.setBackground(txt_username.getBackground());
            txt_pass.setForeground(txt_username.getForeground());
        } else {
            if (txt_pass.getText().length() <= 3) {
                txt_pass.setBackground(Color.red);
                txt_pass.setForeground(Color.white);
            } else if (txt_pass.getText().length() > 3 && txt_pass.getText().length() < 6) {
                txt_pass.setBackground(Color.yellow);
                txt_pass.setForeground(Color.black);
            } else {
                txt_pass.setBackground(txt_username.getBackground());
                txt_pass.setForeground(txt_username.getForeground());
            }
        }
    }//GEN-LAST:event_txt_passKeyReleased

    public void updateUser() {
        try {
            if ("".equals(txt_id.getText()) || "".equals(txt_username.getText()) || "".equals(txt_pass.getText()) || "".equals(txt_rep_pass.getText())) {
                JOptionPane.showMessageDialog(null, "<html><h1>¡CUIDADO FALTAN DATOS!</h1><font SIZE=5><p> Falta escribir algún dato en tu formulario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
            } else if (!txt_pass.getText().equals(txt_rep_pass.getText())) {
                JOptionPane.showMessageDialog(null, "<html><h1>CONTRASEÑAS NO COINCIDEN</h1><font SIZE=5><p> verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
                txt_rep_pass.setText("");
                txt_rep_pass.requestFocus();
            } else {
                String nuevo_registro = txt_id.getText() + "," + txt_username.getText().replace(',', ' ') + "," + txt_pass.getText().replace(',', ' ') + "," + cmbRole.getSelectedItem().toString() + ",";
                if (new Usuarios().UpdateUser(nuevo_registro)) {
                    JOptionPane.showMessageDialog(null, "<html><h1>CUENTA ACTUALIZADA CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void storeUser() {
        if ("".equals(txt_id.getText()) || "".equals(txt_username.getText()) || "".equals(txt_pass.getText()) || "".equals(txt_rep_pass.getText())) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡CUIDADO FALTAN DATOS!</h1><font SIZE=5><p> Falta escribir algún dato en tu formulario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        } else if (!txt_pass.getText().equals(txt_rep_pass.getText())) {
            JOptionPane.showMessageDialog(null, "<html><h1>LAS CONTRASEÑAS NO COINCIDEN</h1><font SIZE=5><p> verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
            txt_rep_pass.setText("");
            txt_rep_pass.requestFocus();
        } else {
            if (new Usuarios().existUser(txt_username.getText().replace(',', ' '))) {
                JOptionPane.showMessageDialog(this, "<html><h1>ESTE USUARIO YA EXISTE!</h1><font SIZE=5><p>El usuario " + txt_username.getText().replace(',', ' ') + " ya esta registrado... vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
                txt_username.requestFocus();
            } else {
                int dialogButton = JOptionPane.showConfirmDialog(null, "<html><h1>¿CREAR CUENTA?  </h1><font SIZE=5><p> Verifique bien sus datos antes de continuar…</font></html>", "CREAR NUEVA CUENTA", JOptionPane.OK_CANCEL_OPTION);
                if (dialogButton == JOptionPane.OK_OPTION) {
                    String id = new Encryptor().clearText(txt_id.getText().replace(',', ' '));
                    String usuario = new Encryptor().clearText(txt_username.getText().replace(',', ' '));
                    String pwd = new Encryptor().clearText(txt_pass.getText().replace(',', ' '));
                    String nuevo_registro = id + "," + usuario + "," + pwd + "," + cmbRole.getSelectedItem().toString() + ",";
                    if (new Usuarios().InsertUser(nuevo_registro)) {
                        ok = true;
                        JOptionPane.showMessageDialog(null, "<html><h1>CUENTA CREADA CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }

                }
            }
        }
    }
    private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
        if (txt_pass.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_passKeyTyped

    private void txt_rep_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rep_passActionPerformed
        storeUser();
    }//GEN-LAST:event_txt_rep_passActionPerformed

    private void txt_rep_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rep_passKeyReleased
        String cadena = (txt_rep_pass.getText()).toUpperCase();
        txt_rep_pass.setText(cadena);
        if (txt_rep_pass.getText().isEmpty()) {
            txt_rep_pass.setBackground(txt_username.getBackground());
            txt_rep_pass.setForeground(txt_username.getForeground());
        } else {
            if (!txt_rep_pass.getText().equals(txt_pass.getText())) {
                txt_rep_pass.setBackground(Color.red);
                txt_rep_pass.setForeground(Color.white);
            } else {
                txt_rep_pass.setBackground(txt_username.getBackground());
                txt_rep_pass.setForeground(txt_username.getForeground());
            }
        }
    }//GEN-LAST:event_txt_rep_passKeyReleased

    private void txt_rep_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rep_passKeyTyped
        if (txt_rep_pass.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_rep_passKeyTyped

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        txt_pass.requestFocus();
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setContinuar(2);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateUser();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                newUser dialog = new newUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txt_id;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_rep_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
