/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.CSVData;
import Classes.Configurations;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author OSBAL
 */
public class SelectFile extends javax.swing.JDialog {

    /**
     * Creates new form select_file
     */
    public SelectFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        this.setTitle("Seleccione Archivo a Importar");
        this.setLocationRelativeTo(null);
        btnBrowseFile.requestFocus();
        String texto_pres = "<center>Recuerde que el archivo debe estar cerrado, y los datos de las columnas deben tener los tipos de datos correspondientes... "
                + "<p>consulte el manual de usuario para más información.</center><p><P>";
        jLabel3.setText("<html>" + texto_pres + "</html>");
        cargar_logo();

    }

    public void cargar_logo() {
        try {
            lbl_image.setIcon(new Configurations().getExample(lbl_image.getWidth(), lbl_image.getHeight()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpoLayout = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_file = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        lbl_DLayout = new javax.swing.JLabel();
        btnBrowseFile = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_acept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione archivo a importar");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECCIONA EL ARCHIVO A IMPORTAR");

        txt_file.setEditable(false);
        txt_file.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("aaaaaaaa");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl_DLayout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DLayout.setText("Descargar Default Layout");
        lbl_DLayout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_DLayoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_DLayoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_DLayoutMouseExited(evt);
            }
        });

        btnBrowseFile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBrowseFile.setText("...");
        btnBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFileActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_cancel.setText("CANCELAR");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_acept.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_acept.setText("ACEPTAR");
        btn_acept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lbl_DLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_file)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowseFile))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_acept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_file)
                            .addComponent(btnBrowseFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_acept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_DLayout)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFileActionPerformed
        try {
            JFileChooser frame = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo CSV", "csv", "CSV");
            frame.setFileFilter(filtro);
            frame.setAcceptAllFileFilterUsed(false);
            int returnVal = frame.showOpenDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                if (getExtension(frame.getSelectedFile().getAbsolutePath()).equals("csv")) {
                    txt_file.setText(frame.getSelectedFile().getAbsolutePath());
                } else {
                    JOptionPane.showMessageDialog(null, "Extencion no valida, serciorase que el archivo sea CSV...", "¡Atencion!", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBrowseFileActionPerformed

    public String getExtension(String ruta) {
        String resp = "";
        int i = ruta.lastIndexOf('.');
        if (i > 0) {
            resp = ruta.substring(i + 1);
        }
        return resp;
    }

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "<html><h1>--CANCELAR PROCESO--</h1>"
                    + "<font SIZE=5><p>¿Seguro que desea cancelar?<p></font></html>", "¡Atencion!", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_aceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptActionPerformed
        ejecutar();
    }//GEN-LAST:event_btn_aceptActionPerformed

    private void lbl_DLayoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DLayoutMouseEntered
        lbl_DLayout.setForeground(Color.RED);
    }//GEN-LAST:event_lbl_DLayoutMouseEntered

    private void lbl_DLayoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DLayoutMouseExited
        lbl_DLayout.setForeground(Color.black);
    }//GEN-LAST:event_lbl_DLayoutMouseExited

    private void lbl_DLayoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DLayoutMouseClicked
        new CSVData().CreateCSVFile();
    }//GEN-LAST:event_lbl_DLayoutMouseClicked

    public boolean abierto(File af) {
        boolean resp = true;
        try {
            File file = new File(af.getAbsolutePath());
            File sameFileName = new File(af.getAbsolutePath());
            if (file.renameTo(sameFileName)) {
                resp = true;
            } else {
                resp = false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        return resp;
    }

    public boolean compCacillas() {
        boolean resp = false;
        if ("".equals(txt_file.getText())) {
            txt_file.requestFocus();
            resp = true;
        }
        return resp;
    }

    public void ejecutar() {
        try {
            if (!compCacillas()) {
                File af = new File(txt_file.getText());
                if (abierto(af)) {
                    if (af.exists()) {
                        if (new CSVData().isEmptyFile(af.getAbsolutePath())) {
                            this.dispose();
                            SelectCols sc = new SelectCols(null, true);
                            String[] colssel = new CSVData().getHeaderCSV(af.getAbsolutePath());
                            sc.actualizar_combos(colssel);
                            sc.show();
                            if (sc.getFselected() != null) {
                                int[] csel = sc.getFselected();
                                new CSVData().saveDataBase(txt_file.getText(), csel);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Este archivo esta vacio, favor de verificar la ruta y vuelve a intentarlo", "¡ERROR!", JOptionPane.WARNING_MESSAGE);
                            txt_file.setText("");
                            btnBrowseFile.requestFocus();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Este archivo no existe, favor de verificar la ruta y vuelve a intentarlo", "¡ERROR!", JOptionPane.WARNING_MESSAGE);
                        txt_file.setText("");
                        txt_file.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El archivo esta abierto, favor de cerrar el documento antes de cargarlo en la base de datos.", "¡Atencion!", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectFile dialog = new SelectFile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseFile;
    private javax.swing.JButton btn_acept;
    private javax.swing.JButton btn_cancel;
    private javax.swing.ButtonGroup gpoLayout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_DLayout;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_file;
    // End of variables declaration//GEN-END:variables
}
