/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Configurations;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author OSBAL
 */
public class Serial extends javax.swing.JDialog {

    /**
     * Creates new form Serial
     */
    String serial = "";
    int resp = 0;
    boolean cancel = false;

    public boolean isCancel() {
        return cancel;
    }

    public String getSerial() {
        return serial;
    }

    public int getResp() {
        return resp;
    }

    public Serial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        lblDesc.setText("<html>Debe estar en su manual de usuario o en su CD/USB de instalación…<br><br>"
                + "La clave de producto debe tener este formato:<br>"
                + "LICENCIA: XXXX-XXXX-XXXX-XXXXX-XXXX-XXXXX\n</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_serial3 = new javax.swing.JTextField();
        txt_serial4 = new javax.swing.JTextField();
        txt_serial5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_serial0 = new javax.swing.JTextField();
        txt_serial1 = new javax.swing.JTextField();
        txt_serial2 = new javax.swing.JTextField();
        btn_sig = new javax.swing.JButton();
        lblDesc = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtCuenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Licencia");
        setName("Licencia"); // NOI18N
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escribe una licencia de producto...");

        txt_serial3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_serial3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serial3ActionPerformed(evt);
            }
        });
        txt_serial3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serial3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serial3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serial3KeyTyped(evt);
            }
        });

        txt_serial4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_serial4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serial4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serial4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serial4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serial4KeyTyped(evt);
            }
        });

        txt_serial5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_serial5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serial5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serial5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serial5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serial5KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("-");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("-");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("-");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("-");

        txt_serial0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_serial0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serial0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serial0KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serial0KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serial0KeyTyped(evt);
            }
        });

        txt_serial1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_serial1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serial1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serial1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serial1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serial1KeyTyped(evt);
            }
        });

        txt_serial2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_serial2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serial2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serial2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serial2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serial2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_serial0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_serial1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_serial2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_serial3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_serial4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_serial5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_serial0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_serial1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_serial2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_serial3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_serial4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_serial5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_sig.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_sig.setText("SIGUIENTE");
        btn_sig.setEnabled(false);
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });

        lblDesc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesc.setText("texto");
        lblDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });
        txtCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuentaKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Nombre de la cuenta:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Correo de cuenta");

        txtemail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Clave de Licencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_sig)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtCuenta))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtemail)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sig, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_serial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serial3ActionPerformed

    public void exitWindow() {
        this.dispose();
    }

    private void txt_serial0KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial0KeyReleased
        txt_serial0.setText(txt_serial0.getText().replaceAll("[^\\dA-Za-z]", "").toUpperCase());
        if (txt_serial0.getText().length() >= 4) {
            txt_serial1.requestFocus();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial0KeyReleased

    private void txt_serial1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial1KeyReleased
        txt_serial1.setText(txt_serial1.getText().replaceAll("[^\\dA-Za-z]", "").toUpperCase());
        if (txt_serial1.getText().length() >= 4) {
            txt_serial2.requestFocus();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial1KeyReleased

    private void txt_serial2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial2KeyReleased
        txt_serial2.setText(txt_serial2.getText().replaceAll("[^\\dA-Za-z]", "").toUpperCase());
        if (txt_serial2.getText().length() >= 4) {
            txt_serial3.requestFocus();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial2KeyReleased

    private void txt_serial3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial3KeyTyped
        if (txt_serial3.getText().length() >= 4) {
            evt.consume();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial3KeyTyped

    private void txt_serial4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial4KeyReleased
        txt_serial4.setText(txt_serial4.getText().replaceAll("[^\\dA-Za-z]", "").toUpperCase());
        if (txt_serial4.getText().length() >= 4) {
            txt_serial5.requestFocus();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial4KeyReleased

    private void txt_serial5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial5KeyTyped
        if (txt_serial5.getText().length() >= 5) {
            evt.consume();
        }
        act_sig();

    }//GEN-LAST:event_txt_serial5KeyTyped

    public void act_sig() {
        if (!"".equals(txt_serial0.getText()) && !"".equals(txt_serial1.getText()) && !"".equals(txt_serial2.getText()) && !"".equals(txt_serial3.getText()) && !"".equals(txt_serial4.getText()) && !"".equals(txt_serial5.getText())) {
            if (txt_serial0.getText().length() == 4 && txt_serial1.getText().length() == 4 && txt_serial2.getText().length() == 4 && txt_serial3.getText().length() == 4 && txt_serial4.getText().length() == 4 && txt_serial5.getText().length() == 5) {
                if (!txtCuenta.getText().equals("") && !txtemail.getText().equals("")) {
                    btn_sig.setEnabled(true);
                } else {
                    btn_sig.setEnabled(false);
                }
            } else {
                btn_sig.setEnabled(false);
            }
        } else {
            btn_sig.setEnabled(false);
        }
    }

    private void txt_serial3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial3KeyReleased
        txt_serial3.setText(txt_serial3.getText().replaceAll("[^\\dA-Za-z]", "").toUpperCase());
        if (txt_serial3.getText().length() >= 4) {
            txt_serial4.requestFocus();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial3KeyReleased

    private void txt_serial5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial5KeyReleased
        txt_serial5.setText(txt_serial5.getText().replaceAll("[^\\dA-Za-z]", "").toUpperCase());
        act_sig();
    }//GEN-LAST:event_txt_serial5KeyReleased

    private void txt_serial0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial0KeyTyped
        if (txt_serial0.getText().length() >= 4) {
            evt.consume();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial0KeyTyped

    private void txt_serial1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial1KeyTyped
        if (txt_serial1.getText().length() >= 4) {
            evt.consume();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial1KeyTyped

    private void txt_serial2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial2KeyTyped
        if (txt_serial2.getText().length() >= 4) {
            evt.consume();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial2KeyTyped

    private void txt_serial4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial4KeyTyped
        if (txt_serial4.getText().length() >= 4) {
            evt.consume();
        }
        act_sig();
    }//GEN-LAST:event_txt_serial4KeyTyped

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
        String[] serial = {txt_serial0.getText(), txt_serial1.getText(), txt_serial2.getText(), txt_serial3.getText(), txt_serial4.getText(), txt_serial5.getText()};
        if (new Configurations().verifyLicense(serial) == true) {
            resp = 1;
            String serl = serial[0] + "-" + serial[1] + "-" + serial[2] + "-" + serial[3] + "-" + serial[4] + "-" + serial[5];
            new Configurations().setLicData(txtCuenta.getText().replace(",", ""), txtemail.getText(), serl);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "<html><h1>--CLAVE DE PRODUCTO NO VALIDA--</h1>"
                    + "<font SIZE=5><p>Verifiquelo y no vuelve a intentarlo...<p></font></html>", "ATENCION!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_sigActionPerformed


    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancelProcess();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyReleased
        act_sig();
    }//GEN-LAST:event_txtCuentaKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        act_sig();
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txtCuentaKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txtemailKeyPressed

    private void txt_serial0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial0KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txt_serial0KeyPressed

    private void txt_serial1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txt_serial1KeyPressed

    private void txt_serial2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txt_serial2KeyPressed

    private void txt_serial3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txt_serial3KeyPressed

    private void txt_serial4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txt_serial4KeyPressed

    private void txt_serial5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serial5KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            cancelProcess();
        }
    }//GEN-LAST:event_txt_serial5KeyPressed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        txtemail.requestFocus();
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        txt_serial0.requestFocus();
    }//GEN-LAST:event_txtemailActionPerformed

    public void cancelProcess() {
        int resp = JOptionPane.showConfirmDialog(null, "<html><h1>--TERMINAR PROCESO--</h1>"
                + "<font SIZE=5><p>¿Seguro que desea cancelar?<p></font></html>", "¡Atencion!", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            System.exit(resp);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Serial dialog = new Serial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btn_sig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txt_serial0;
    private javax.swing.JTextField txt_serial1;
    private javax.swing.JTextField txt_serial2;
    private javax.swing.JTextField txt_serial3;
    private javax.swing.JTextField txt_serial4;
    private javax.swing.JTextField txt_serial5;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
