/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.generalControls;

import Classes.*;
import frames.adminControls.adminHome;
import frames.userControls.userHome;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author terra
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form session
     */
    public Login() {
        this.setUndecorated(true);
        initComponents();
        setIconImage(new Configurations().getImageIcon().getImage());
        this.setLocationRelativeTo(null);
        if (!new Configurations().isActivated()) {
            this.setUnActivated();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pasword = new javax.swing.JPasswordField();
        btnLoggin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicia sesión");

        pnlBase.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña");

        txt_user.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_userKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userKeyTyped(evt);
            }
        });

        txt_pasword.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_pasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paswordActionPerformed(evt);
            }
        });
        txt_pasword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_paswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_paswordKeyTyped(evt);
            }
        });

        btnLoggin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLoggin.setText("INGRESAR");
        btnLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogginActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIA SESION");

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLoggin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pasword)
                            .addComponent(txt_user))))
                .addContainerGap())
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        salir();
    }//GEN-LAST:event_btnExitActionPerformed

    public void salir() {
        int resp = JOptionPane.showConfirmDialog(null, "<html><h1>¡Usted está a punto de salir!...</h1><font SIZE=5><p>¿Está seguro que desea cerrar la aplicación?</font></html>", "", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            System.exit(resp);
        }
    }

    private void btnLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogginActionPerformed
        if ("".equals(txt_user.getText())) {
            JOptionPane.showMessageDialog(null, "Falta escribir el nombre del usuario", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        } else if ("".equals(txt_pasword.getText())) {
            JOptionPane.showMessageDialog(null, "Falta escribir la contraseña", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        } else {
            String user = txt_user.getText().replace(',', ' ');
            String pwd = txt_pasword.getText().replace(',', ' ');
            inicio_sesion(user, pwd);
        }
    }//GEN-LAST:event_btnLogginActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        txt_pasword.requestFocus();
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_paswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paswordActionPerformed
        if ("".equals(txt_user.getText())) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡Cuidado faltan datos!</h1><font SIZE=5><p>Falta escribir el nombre del usuario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        } else if ("".equals(txt_pasword.getText())) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡Cuidado faltan datos!</h1><font SIZE=5><p>Falta escribir la contraseña, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        } else {
            String user = txt_user.getText();
            String pwd = txt_pasword.getText();
            inicio_sesion(user, pwd);
        }
    }//GEN-LAST:event_txt_paswordActionPerformed

    private void txt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyTyped
        if (txt_user.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_userKeyTyped

    private void txt_paswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paswordKeyTyped
        if (txt_pasword.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_paswordKeyTyped

    private void txt_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyReleased

    }//GEN-LAST:event_txt_userKeyReleased

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            salir();
        }
    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_paswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            salir();
        }
    }//GEN-LAST:event_txt_paswordKeyPressed

    public void setUnActivated() {
        pnlBase.setBackground(Color.WHITE);
    }

    public void upTryalVersion() {
        if (!new Configurations().isActivated() && !new Sesiones().areLogginsAtDay(new SimpleDateFormat("dd-MM-YYYY").format(new Date()))) {
            new Configurations().upTryalDays();
        }
    }

    public void inicio_sesion(String usuario, String contraseña) {
        try {
            System.out.println("login");
            if (new Usuarios().confirmar_acceso(usuario, contraseña)) {
                String id = new Sesiones().genID();
                upTryalVersion();
                new Sesiones().saveRegSession(id, usuario);
                String[] User = new Usuarios().findUserbyName(usuario);
                System.out.println("user"+User);
                if (User[3].equals("Administrador") || User[3].equals("root")) {
                    adminHome m = new adminHome();
                    m.Inicialize(usuario, User[3]);
                    m.show();
                } else {
                    userHome m = new userHome();
                    m.Inicialize(usuario, User[3]);
                    m.show();
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "<html><h1>¡ACCESO DENEGADO!</h1><font SIZE=5><p>Verifique sus credenciales y vuelva a intentarlo...</font></html>", "", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoggin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPasswordField txt_pasword;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
